-- Create database (run manually)
-- CREATE DATABASE online_judge;

-- Users table
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    email VARCHAR(255) UNIQUE,
    password VARCHAR(255),
    role VARCHAR(20) NOT NULL DEFAULT 'USER',
    total_solved INT DEFAULT 0,
    total_submissions INT DEFAULT 0,
    score INT DEFAULT 0,
    stars INT DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Problems table
DROP TABLE IF EXISTS test_cases;
DROP TABLE IF EXISTS problem_notes;
DROP TABLE IF EXISTS submissions;
DROP TABLE IF EXISTS contest_problems;
DROP TABLE IF EXISTS contest_participants;
DROP TABLE IF EXISTS problems;
CREATE TABLE problems (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    problem_code VARCHAR(20),
    title VARCHAR(255) NOT NULL,
    statement TEXT,
    description TEXT NOT NULL,
    difficulty VARCHAR(20) NOT NULL,
    level VARCHAR(20),
    topic_tags TEXT,
    topics TEXT,
    companies VARCHAR(255),
    platform VARCHAR(100),
    input_format TEXT,
    output_format TEXT,
    constraints TEXT,
    sample_input TEXT,
    sample_output TEXT,
    sample_explanation TEXT,
    time_limit_ms INT DEFAULT 2000,
    memory_limit_mb INT DEFAULT 256,
    category VARCHAR(100) DEFAULT 'General',
    family VARCHAR(100),
    kind VARCHAR(50),
    starter_code TEXT,
    submissions INT DEFAULT 0,
    acceptance_rate NUMERIC(5,2),
    total_submissions INT DEFAULT 0,
    accepted_submissions INT DEFAULT 0,
    intuition TEXT,
    approach TEXT,
    algorithm TEXT,
    syntax_notes TEXT,
    hints TEXT,
    editorial TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Test cases table
CREATE TABLE IF NOT EXISTS test_cases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    problem_id BIGINT NOT NULL REFERENCES problems(id) ON DELETE CASCADE,
    input TEXT NOT NULL,
    expected_output TEXT NOT NULL,
    explanation TEXT,
    is_sample BOOLEAN DEFAULT FALSE,
    order_index INT DEFAULT 0
);

-- Problem notes table
CREATE TABLE IF NOT EXISTS problem_notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    problem_id BIGINT NOT NULL REFERENCES problems(id) ON DELETE CASCADE,
    approach TEXT,
    logic TEXT,
    learnings TEXT,
    time_complexity VARCHAR(50),
    space_complexity VARCHAR(50),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_problem_notes_user_problem UNIQUE (user_id, problem_id)
);

-- Submissions table
CREATE TABLE IF NOT EXISTS submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    problem_id BIGINT NOT NULL REFERENCES problems(id) ON DELETE CASCADE,
    code TEXT NOT NULL,
    language VARCHAR(20) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    execution_time_ms INT,
    memory_used_kb INT,
    output TEXT,
    error_message TEXT,
    test_cases_passed INT DEFAULT 0,
    total_test_cases INT DEFAULT 0,
    score_earned INT DEFAULT 0,
    stars_earned INT DEFAULT 0,
    submitted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Contests table
CREATE TABLE IF NOT EXISTS contests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    start_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    end_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    duration_minutes INT NOT NULL DEFAULT 90,
    status VARCHAR(20) DEFAULT 'UPCOMING',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Contest to problems mapping
CREATE TABLE IF NOT EXISTS contest_problems (
    contest_id BIGINT NOT NULL REFERENCES contests(id) ON DELETE CASCADE,
    problem_id BIGINT NOT NULL REFERENCES problems(id) ON DELETE CASCADE,
    PRIMARY KEY (contest_id, problem_id)
);

-- Contest participants mapping
CREATE TABLE IF NOT EXISTS contest_participants (
    contest_id BIGINT NOT NULL REFERENCES contests(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    PRIMARY KEY (contest_id, user_id)
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_problems_problem_code ON problems(problem_code);
CREATE INDEX IF NOT EXISTS idx_submissions_user_id ON submissions(user_id);
CREATE INDEX IF NOT EXISTS idx_submissions_problem_id ON submissions(problem_id);
CREATE INDEX IF NOT EXISTS idx_problems_difficulty ON problems(difficulty);
CREATE INDEX IF NOT EXISTS idx_problems_category ON problems(category);
CREATE INDEX IF NOT EXISTS idx_problem_notes_user_id ON problem_notes(user_id);
CREATE INDEX IF NOT EXISTS idx_problem_notes_problem_id ON problem_notes(problem_id);
CREATE INDEX IF NOT EXISTS idx_users_score ON users(score);
